# Generated by Django 2.2.1 on 2020-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('current_x', models.PositiveIntegerField(default=0)),
                ('current_y', models.PositiveIntegerField(default=0)),
                ('booked', models.BooleanField(default=True)),
            ],
        ),
    ]
