# Generated by Django 2.2.1 on 2020-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
