# Generated by Django 2.2.1 on 2020-07-20 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.PositiveIntegerField(default=0)),
                ('start_y', models.PositiveIntegerField(default=0)),
                ('end_x', models.PositiveIntegerField(default=0)),
                ('end_y', models.PositiveIntegerField(default=0)),
                ('craeted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driver.Driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
        ),
    ]
