# Generated by Django 2.2.1 on 2020-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='running_status',
            field=models.BooleanField(default=False),
        ),
    ]
