# Generated by Django 2.2.1 on 2020-07-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_ride_running_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='running_status',
            new_name='complete',
        ),
    ]
